### PR TITLE
Fix backspace & tab keys in IE

### LINKED ISSUE #569: bug using backspace in Internet Explorer
When using IE 11 on Windows 7, if you press backspace (such as when logging into and correcting your cloud account name or password), the program tries to exit by giving you the "leaving page" question.  For this reason, I cannot recommend using IE to my students.

### PR DESCRIPTION
**Pull request by bl-nero**
Fixes #569 

Tested on:

* Chrome 46.0.2490.71 (Mac)
* Firefox 41.0.1 (Mac)
* Opera 32.0 (Mac)
* IE 11 (Win 8.1)

(Note: pasting doesn't work outside Chrome, but it looks like it has never worked anyway.)

### CODE REVIEW

File: morphic.js [hunk 1]
```diff
@@ -10224,14 +10224,12 @@ WorldMorph.prototype.initVirtualKeyboard = function () {
                 myself.keyboardReceiver.processKeyDown(event);
             }
             // supress backspace override
-            if (event.keyIdentifier === 'U+0008' ||
-                    event.keyIdentifier === 'Backspace') {
+            if (event.keyCode === 8) {
```
Comment (jmoenig) [inline morphic.js]: really? *that* solves it? Fantastic, thank you!

**Comment by jmoenig** [comment]
Thank you so much! I'm travelling this week, not sure whether or when I'll have time to work on Snap, but I *will* pull this next thing!

File: morphic.js (hunk 1 above)
Comment (bl-nero) [inline morphic.js]: I couldn't believe it either, because it's been a while since I touched such low-level stuff, but it looks like the support for `key` and `keyIdentifier` properties is vastly inconsistent among browsers. Even though they were supposed to replace `keyCode`, the latter is still the simplest way to solve it.
