### PR TITLE
Fixing ColorSlotMorphs behavior in Visible Stepping

### LINKED ISSUE #1499: Visual Stepping involuntarily changes sprite and pen color
I've noticed when I turn on "Visual Stepping" the sprite changes its color to a light teal color. And any "Pen Down" line colors are also the same light teal color, regardless of any command to change the pen color.

Please advise.

### PR DESCRIPTION
**Pull request by jguille2**
This PR fix #1499 

Visual Stepping flash ColorSlotMorph, and the execution of the block is with the wrong color (uses the "flashing color" and not slot/input color).

### CODE REVIEW

File: threads.js [hunk 1]
```diff
@@ -3357,7 +3357,8 @@ Process.prototype.flashContext = function () {
             expr instanceof SyntaxElementMorph &&
             !(expr instanceof CommandSlotMorph) &&
             !this.context.isFlashing &&
-            expr.world()) {
+            expr.world() &&
+			!(expr instanceof ColorSlotMorph)) {
```
Comment (cycomachead) [inline threads.js]: We don't need to indent this as much.

**Comment by jmoenig** [comment]
excellent analysis and great catch. Thank you, @jguille2 !
