### PR TITLE
Fixed #1428, an issue with preview the (empty) project placeholder.

### LINKED ISSUE #1428: JS Error on previewing (empty) project
To reproduce:
* Open snap in a private tab (to "clear" you browser cache)
* Open the JS console
* Go to File -> Open -> Browser
* Select the "(empty)" project
* You'll see the error in the console: `Expected "=" after attribute name`

Not a show-stopper, for sure, but it does cause an annoying error (that looks pretty scary in logs). I'm submitting a quick fix in a pull request.

### PR DESCRIPTION
**Pull request by thomaswp**
Quick fix for #1428. The current code treats the "(empty)" placeholder the same as any other project and attempts to open it, leading to a parse error. This checks first and does nothing for invalid projects.

### CODE REVIEW

File: gui.js [hunk 1]
```diff
@@ -5440,16 +5440,19 @@ ProjectDialogMorph.prototype.setSource = function (source) {
...
-                myself.notesText.text = xml.childNamed('notes').contents
-                    || '';
-                myself.notesText.drawNew();
-                myself.notesField.contents.adjustBounds();
-                myself.preview.texture = xml.childNamed('thumbnail').contents
-                    || null;
-                myself.preview.cachedTexture = null;
-                myself.preview.drawNew();
+
+                if (src) {
```
Comment (jmoenig) [inline gui.js]: duh! :-)

**Comment by jmoenig** [comment]
Thanks for this fix, Thomas! I'll pull it and integrate it into the next release, but since I'm both travelling and probably switching day-jobs at the moment this might take me some days or even weeks. I've marked this PR with my "blessing" so I'll bulk-pull all before the next release gets out.
