### PR TITLE
fixes #1860 (var refactor issue)

### LINKED ISSUE #1860: Refactor-renaming a parameter that has a type or default value not working
The rename input should hide the extra characters and only display the parameter _name_.

### PR DESCRIPTION
**Pull request by bromagosa**

### CODE REVIEW

File: blocks.js [hunk 1]
```diff
@@ -3216,7 +3216,7 @@ BlockMorph.prototype.refactorThisVar = function (justTheTemplate) {
     // taking care of its lexical scope
 
     var receiver = this.scriptTarget(),
-        oldName = this.blockSpec,
+        oldName = this.instantiationSpec || this.blockSpec,
```
Comment (jmoenig) [inline blocks.js]: wait! that was the whole fix?! Yay, thanks!

**Comment by jmoenig** [comment]
thanks, Bernat! I'll pull it on Monday.
